// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDet9ltZ30YC-Liio9MvqU5DuAaMuQQRmQ',
    appId: '1:499337562137:web:2a3afa28100bad5c880288',
    messagingSenderId: '499337562137',
    projectId: 'mad-2022-26-34684',
    authDomain: 'mad-2022-26-34684.firebaseapp.com',
    storageBucket: 'mad-2022-26-34684.firebasestorage.app',
    measurementId: 'G-BJLD79JVTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiR3pQOFkVMYtuyERrqkpE9FtlHuJrcSc',
    appId: '1:499337562137:android:be182fa59b141f61880288',
    messagingSenderId: '499337562137',
    projectId: 'mad-2022-26-34684',
    storageBucket: 'mad-2022-26-34684.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPgVAqPLKypRFqga9iFYYR4-zj1yxifPc',
    appId: '1:499337562137:ios:780502714ee39920880288',
    messagingSenderId: '499337562137',
    projectId: 'mad-2022-26-34684',
    storageBucket: 'mad-2022-26-34684.firebasestorage.app',
    iosBundleId: 'com.example.mad202226',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPgVAqPLKypRFqga9iFYYR4-zj1yxifPc',
    appId: '1:499337562137:ios:780502714ee39920880288',
    messagingSenderId: '499337562137',
    projectId: 'mad-2022-26-34684',
    storageBucket: 'mad-2022-26-34684.firebasestorage.app',
    iosBundleId: 'com.example.mad202226',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDet9ltZ30YC-Liio9MvqU5DuAaMuQQRmQ',
    appId: '1:499337562137:web:9f5869f8bcd9963a880288',
    messagingSenderId: '499337562137',
    projectId: 'mad-2022-26-34684',
    authDomain: 'mad-2022-26-34684.firebaseapp.com',
    storageBucket: 'mad-2022-26-34684.firebasestorage.app',
    measurementId: 'G-LP247KVL5F',
  );
}
